import { StyleSheet } from "react-native";

export default StyleSheet.create({
  header: {
    backgroundColor: "#3c9fd9",
    height: 160,
    zIndex: 0,
    // borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  headerbottom:{
    backgroundColor: "white",
    height: 50,
    zIndex: 0,
    borderTopLeftRadius: 40,
    // borderBottomRightRadius: 40,
  },

  topBlue: {
    height: 150,
    backgroundColor: "blue",
    borderBottomRightRadius: 40,
    // transform: [{ rotate: "10deg" }],
    position: "relative",
  },
  cheatBlue: {
    height: 100,
    zIndex: 2,
    width: 150,
    backgroundColor: "blue",
    position: "absolute",
    bottom: -50,
    left: 0,
  },
  bannerBg: {
    width: "100%",
    height: "100%",
    backgroundColor: "#209FD9",
  },

  topBackBtn: {
    width: 20,
    height: 20,
    backgroundColor: "white",
    position: "absolute",
    zIndex: 5,
    left: 25,
    top: 25,
    padding: 3,
    borderRadius: 2,
  },
  topBackIcon: {
    height: "100%",
    width: "100%",
    shadowColor: "red",
  },
  topSearchBtn: {
    width: 20,
    height: 20,
    backgroundColor: "white",
    position: "absolute",
    zIndex: 5,
    right: 25,
    top: 25,
    padding: 3,
    borderRadius: 2,
  },
  headerBgIcon: {
    width: "100%",
    resizeMode: "contain",
    position: "absolute",
    bottom: -40,
    zIndex: 2,
  },
  curveHeader: {
    width: "100%",
    position: "absolute",
    left: -1,
    top: 80,
    height: 25,
    zIndex: 3,
    transform: [{ rotate: "5deg" }],
    backgroundColor: "transparent",
  },
  logoBox: {
    position: "absolute",
    top: 50,
    left: 10,
    width: 130,
    height: 82,
    // backgroundColor: "red",
    zIndex: 5,
    padding: 10,
    marginLeft: 20,
  },
  logoBoxIcon: {
    width: 25,
    height: 30,
    padding: 2,
  },
  logoBoxMulti: {
    position: "absolute",
    top: 90,
    left: 10,
    width: "auto",
    height: 82,
    zIndex: 5,
    padding: 10,
    marginLeft: 20,
  },
  logoBoxIconText: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  logoImg: {
    width: "100%",
    height: "100%",
  },
  logoText: {
    fontWeight: "bold",
    marginLeft: 10,
    color: "white",
    fontSize: 18,
    textTransform: "capitalize",
  },
  footer: {
    position: "relative",
    marginHorizontal: 5,
  },
  footerBody: {
    backgroundColor: "#219FD9",

    display: "flex",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    position: "absolute",
    zIndex: 1,
    width: "100%",
    bottom: 0,
    alignItems: "center",
  },
  footerContent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 15,
  },
  footerIcons: {
    width: "25%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  eachFooterIcon: {
    width: 25,
    height: 25,
    opacity: 0.5,
  },
  currentSection: {
    opacity: 1,
  },
  inputArea: {
    // backgroundColor: "#DFF3FC",
    padding: 4,
    paddingLeft: 10,
    borderRadius: 5,
    marginTop: 5,
    overflow: "hidden",
    width: "100%",
  },
  touchableBtn: {
    backgroundColor: "#219FD9",
    padding: 10,
    borderRadius: 10,
    marginVertical: 5,
  },
  touchableBtnTxt: {
    color: "white",
    textAlign: "center",
    textTransform: "capitalize",
    fontSize: 17,
    fontWeight: "bold",
    letterSpacing: 0.2,
  },
  topCounterHeader: {
    backgroundColor: "black",
    color: "white",
    textAlignVertical: "center",
    marginLeft: 15,
    width: "auto",
    paddingHorizontal: 5,
    fontSize: 13,
    marginTop: 2,
    borderRadius: 5,
  },
  checkboxOut:{
    flexDirection: 'row',
    alignItems: 'center'
  }
});
